### PR TITLE
FEATURE(Motion): Free arm position

### PR DESCRIPTION
**Pull request by davidfolch**
With this feature the user can turn on the saber from any position. 

### Compatibility with original turn on method
When saber is in vertical position it applies the original roll sensibility and wait to config or confirm arm when saber is at non-vertical position and is not swinging.

### How to use
As alternative, the user can turn on the saber from any non-vertical position with hard roll (it has less sensibility), with this method it confirm turn on instantly

### ¿Why?
This allows turn on the saber faster and more comfortably, and also allows whoever uses saberstaff turn on both parts at the same time.

### CODE REVIEW

**Comment by FarFlyer** [comment]
Hello and thanks for the proposal. It's more than welcome since we have been asked a lot a better arming for the saberstaff.

There is just one thing that shall be modified to be accepted and merged in the main official branch.
With your current change, it is possible to arm the saber starting from the vertical position and rotate just 45deg (tip pointing upward).
This shall be changed: the arming starting from the vertical position (tip pointing upwards) must be at 45deg with the tip pointing downwards.
Please check the `case LP_ARM` in the CoreMotion.cpp

If you want to apply the same for the saberstaff, the blade this points downwards shall be armed when the tip points upwards.

**Comment by davidfolch** [comment]
@FarFlyer That is precisely the point of this feature. Only while it is vertical can you access the saber configuration, and in any other position it turns on directly.

This allows for quick turn on and allows both parts of the saberstaff to be turned on at the same time as long as they are not pointing upwards. If I kept the armed position at -45º, this whole feature loses its meaning

**Comment by FarFlyer** [comment]
@davidfolch the arming at any position works great.
My only concern is that only the vertical arming shall be with the movement at 45 degree pointing downward.

**Comment by davidfolch** [comment]
@FarFlyer It's hard trying to keep confirmation of -45 degrees with this feature. The reason is that the gyroscope goes crazy when doing a hard roll and if you try to read the Z position of the saber at the moment it returns an incorrect orientation. With current code this doesn't matter as there is a timeout for the arming confirmation after the roll. To maintain -45 degrees in this confirmation I would have to divide the cases of fast turn on and vertical turn on, I have tried to do it by setting a variable in EVT_ARM when user rolls the saber that indicates the type of turn on according to the orientation, and filtering confirm position only when is in vertical turn on, the problem is that this doesn't always work well, since when making a hard roll in vertical position it sometimes detects that it is not vertical and turns on directly, and sometimes when turning on from any other position it detects it as vertical and waits for confirmation. This generates a very bad experience so it is not viable.
I hope I have explained myself clearly, if it occurs to some of you how to solve it you can complete it from this code, or if you have any advice it is welcome.
Just out of curiosity, is there a reason to keep this confirm orientation? After trying it for several days I feel much more comfortable that it confirm as soon as I leave the vertical range

**Comment by FarFlyer** [comment]
Thanks, @davidfolch for the detailed explanation. I see your point.
The reason to keep the confirm orientation it's related to the "saluto" gesture at the beginning of a match. The tip pointing downward it's the "invito" stance.
It would have been nice to have this feature selectable via a parameter in the settings, but it'll create a complex code.
From my perspective, this implementation is very good and valuable.
The council will judge in the upcoming days.

**Comment by davidfolch** [comment]
@FarFlyer it is still really compatible with the salute, it is confirmed when the swing stops. It can be in another position, but it is also possible to do it at -45 degrees, just as it is you can confirm it wherever you want, if you lower it directly to -45 degrees it will not the difference to the original code is noticeable

**Review by FarFlyer — APPROVED** [review]
Thanks for this enhancement. It's been accepted by LamaDiLuce as official.

**Comment by davidfolch** [comment]
Hi @FarFlyer , just to make sure, you have accepted the old MR that when it turns on vertically confirms leaving this vertical zone, and you closed the new one that does it at -45 degrees as you wanted, is this correct? The new one also refactored the state management for an instant turn-on without the flickering it currently does in this branch before turning on.

**Pull request merged**
