### PR TITLE
Refactor:  Improve Quick Ignition

### PR DESCRIPTION
**Pull request by davidfolch**
## Description
Previously, even if the quick ignition method was used, the lightsaber still went through the configuration state before turning on. This was because the code did not allow a direct transition from the idle state to the armed state. To resolve this, I refactored the quick ignition functionality to enable the jump between the idle and armed states, so the lightsaber now turns on directly without passing through the configuration state.

To achieve this, I encountered two problems. First, when the lightsaber is quickly ignited, the gyroscope loses precision and reads an incorrect position, which can lead to the lightsaber being mistakenly identified as being in a vertical position when it is not. To address this, I updated the code to only read the lightsaber's position when it is not rotating and store this information for a split second, so that the previous accurate position is used when the lightsaber is ignited quickly.

Second, the fade-in of the light used to occur when leaving the arm state, but with the new flow of states, it needs to occur when leaving the idle state. To maintain a consistent user experience, I added fade-ins and fade-outs to both the color blinking that occurs when entering the configuration state and when changing colors during color selection.

With these changes, the quick ignition functionality has been greatly improved, resulting in a smoother and more seamless experience.

## Changes Made
- Enabled direct transition from idle to armed state for quick ignition functionality
- Updated code to address gyroscope precision loss during quick ignition
- Added fade-ins and fade-outs to maintain consistent user experience

### CODE REVIEW

**Comment by jramboz** [comment]
Beautiful work, @davidfolch! And just in time for my Form 1 class tonight. I've compiled and put it on my sabers, and I'll let you know how it does in testing tonight.

**Comment by FarFlyer** [comment]
@davidfolch thanks for the refactoring, excellent job.
I found one situation that triggers a spurious arm. It's when I perform an F2 "semiaffondo" in "autorità" position aiming with the blade's tip slightly pointing upwards. It's strange because it triggers the ARM state, not the ARMED (thus waiting for the -45 degree position for arming).
Do you have some hints on improving this point?

For the fadeout at the first flash and during the color change I'll come back after a discussion with LDL. I like it between colors, maybe the first flash can be without the fadeout.

BTW are you on the discord server? I cannot find you.

**Comment by davidfolch** [comment]
> @davidfolch thanks for the refactoring, excellent job.
> I found one situation that triggers a spurious arm. It's when I perform an F2 "semiaffondo" in "autorità" position aiming with the blade's tip slightly pointing upwards. It's strange because it triggers the ARM state, not the ARMED (thus waiting for the -45 degree position for arming).
> Do you have some hints on improving this point?
> 
> For the fadeout at the first flash and during the color change I'll come back after a discussion with LDL. I like it between colors, maybe the first flash can be without the fadeout.
> 
> BTW are you on the discord server? I cannot find you.

In fact I wrote you a few days ago by discord (I'm Crede) when the previous MR was rejected to see how to improve it. Look at the private messages hehe.

About the fact that it turns on as if it were vertical when it is not was what I intended to correct by saving the vertical timer when the saber is not rotating, because while it rotates it loses the precision of its position, it has improved but it seems that it still does not go 100% correctly, I still think that the problem comes from there, I can think of a possible solution that I will try this afternoon. Ideas on this subject are welcome.

As for the fade-out precisely when it enters the Arm state is the one that has to be maintained for technical reasons, since the execution must be done when leaving the Idle state, before knowing if it will go to the configuration or the final ignition, in case of entering the configuration makes the fadeout, and if it enters the armed it keeps it on. To do it as you say would have to add a new state "arming" that is the one that makes the fade-in of ignition and that the state "arm" has its own on and off without fadein or fadeout, and it seems to me to add a lot of complex code to the feature. It can be done, but I would do it as a later enhancement.

**Comment by davidfolch** [comment]
Well, about de fades, i can keep the fade-in but turn off without fade-out on enter at arm state, is that what you meant?

**Comment by FarFlyer** [comment]
> Well, about de fades, i can keep the fade-in but turn off without fade-out on enter at arm state, is that what you meant?

Yes!

**Review by FarFlyer — APPROVED** [review]

**Pull request merged**
